### ISSUE TITLE
6.0.4 ZEO tests are failing

### ISSUE THREAD

**Issue by avoinea** [eea/plone-backend#5]
```
Using ZEO configuration
Traceback (most recent call last):
  File "/app/bin/runwsgi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/serve.py", line 251, in main
    return command.run()
           ^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 273, in loadobj
    return context.create()
           ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 200, in invoke
    app = context.app_context.create()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 138, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/paste/deploy/util.py", line 61, in fix_call
    val = callable(*args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/run.py", line 61, in make_wsgi_app
    starter.prepare()
  File "/app/lib/python3.11/site-packages/Zope2/Startup/starter.py", line 38, in prepare
    self.startZope()
  File "/app/lib/python3.11/site-packages/Zope2/Startup/starter.py", line 94, in startZope
    Zope2.startup_wsgi()
  File "/app/lib/python3.11/site-packages/Zope2/__init__.py", line 36, in startup_wsgi
    _startup()
  File "/app/lib/python3.11/site-packages/Zope2/App/startup.py", line 100, in startup
    DB = dbtab.getDatabase('/', is_root=1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/datatypes.py", line 245, in getDatabase
    db = factory.open(name, self.databases)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/datatypes.py", line 141, in open
    DB = self.createDB(database_name, databases)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/Startup/datatypes.py", line 138, in createDB
    return ZODBDatabase.open(self, databases)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/ZODB/config.py", line 146, in open
    storage = section.storage.open()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/ZODB/config.py", line 239, in open
    from ZEO.ClientStorage import ClientStorage
ModuleNotFoundError: No module named 'ZEO'
```

**Comment by avoinea** [comment]
See also: https://github.com/plone/plone-backend/issues/119

**Comment by avoinea** [comment]
Fixed by https://github.com/eea/plone-backend/commit/e1fefba8375f6408fcf082224ba5449b811bd1b8
